service: backend

frameworkVersion: ">=1.1.0 <2.0.0"
provider:
  name: aws
  profile: private
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handler.webook
    memorySize: 128
    description: Handling Webhooks from Particle.io to store  in DynamoDB
    events:
      - http:
          path: particle-webhook
          method: post
          cors: true
      
